;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; DescriptionTable6809.asm
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

description_table
	.db 30
	.strz "YOU NOTICE NOTHING UNEXPECTED." ; 0
	.db 9
	.strz "OFFSCREEN" ; 1
	.db 22
	.strz "YOU SHOULDN'T BE HERE." ; 2
	.db 95
	.strz "YOUR CLOTHES ARE BIT DIRTY FROM YOUR LONG HIKE THROUGH THE WOODS. ASIDE FROM THAT, YOU'RE FINE." ; 3
	.db 61
	.strz "THIS IS THE START OF A PATH THAT WINDS NORTH INTO THE FOREST." ; 4
	.db 80
	.strz "THE HUT IS BARELY LARGE ENOUGH TO PROTECT ONE OR TWO SENTRIES FROM THE ELEMENTS." ; 5
	.db 38
	.strz "A DILAPIDATED GUARD HUT STANDS NEARBY." ; 6
	.db 79
	.strz "YOU ARE INSIDE THE SMALL GUARD HUT. THE OPEN DOORWAY LEADS OUTSIDE TO THE WEST." ; 7
	.db 181
	.strz "YOU ARE AT THE MOUTH OF A LARGE, COLLAPSED TUNNEL CUT INTO A STEEP HILLSIDE TO THE NORTH. A DIRT PATH RUNS EAST AND WEST AROUND THE ESCARPMENT AND WINDS SOUTH INTO THE THICK FOREST." ; 8
	.db 104
	.strz "YOU ARE ON A DIRT PATH CURVING AROUND THE BASE OF A ROCKY HILLSIDE. THE PATH EXTENDS WEST AND NORTHEAST." ; 9
	.db 102
	.strz "YOU ARE ON A DIRT PATH CURVING AROUND THE BASE OF A ROCKY HILLSIDE. THE PATH EXTENDS BACK TO THE EAST." ; 10
	.db 237
	.strz "YOU ARE ON THE EASTERN EDGE OF A ROCKY HILLSIDE.  A LARGE,DARK TUNNEL EXTENDS WESTWARD INTO THE HILLSIDE.  ALTHOUGH IT APPEARS ATTEMPTS WERE MADE TO DEMOLISH IT, IT MAY BE POSSIBLE TO CLIMB OVER THE DEBRIS. A DIRT PATH EXTENDS SOUTHWEST." ; 11
	.db 135
	.strz "YOU ARE ONTOP OF A LARGE ROCK PILE JUST INSIDE THE MOUTH OF A LARGE TUNNEL. TO THE WEST, THE PILE DROPS PRECIPITOUSLY INTO THE DARKESS." ; 12
	.db 149
	.strz "YOU ARE AT THE EASTERN END OF AN EAST-WEST TUNNEL. TO THE EAST, A HUGE DEBRIS PILE, THE RESULT OF INTENTIONAL DEMOLITION, COMPLETELY BLOCKS THE EXIT." ; 13
	.db 67
	.strz "YOU ARE AT A TUNNEL JUNCTION. TUNNELS EXTEND EAST, WEST, AND SOUTH." ; 14
	.db 95
	.strz "THIS IS A SMALL OFFICE AREA. DOORWAYS LEADS NORTH AND SOUTH.  A STORAGE CLOSEST IS TO THE EAST." ; 15
	.db 47
	.strz "THIS IS A DANK LAVATORY. A DOORWAY LEADS NORTH." ; 16
	.db 29
	.strz "THE DOOR SPORTS A LARGE LOCK." ; 17
	.db 52
	.strz "THIS IS A CRAMPED STORAGE CLOSET. A DOOR LEADS WEST." ; 18
	.db 108
	.strz "THIS IS A LONG EAST-WEST TUNNEL THAT SLOPES DOWNWARD TOWARD THE WEST. A SMALLER TUNNEL EXTENDS TO THE NORTH." ; 19
	.db 72
	.strz "THIS IS A FOUR WAY JUNCTION.  PASSAGES LEAD NORTH, SOUTH, EAST AND WEST." ; 20
	.db 185
	.strz "THIS IS A LARGE, NORTH-SOUTH TUNNEL THAT ENDS ABRUPTLY WHERE IT HAS COLLAPSED.  SCORCH MARKS WOULD SUGGEST THE TUNNEL ENTRANCE WAS DESTROYED DELIBERATELY. THE ONLY EXIT IS TO THE NORTH." ; 21
	.db 174
	.strz "YOU HAVE ENTERED A VAST SUBTERANEAN WORKHALL CARVED OUT OF THE NATIVE LIMESTONE. IT WAS APPARENTLY GUTTED OF EQUIPMENT BEFORE IT WAS ABANDONED. THERE IS AN EXIT TO THE SOUTH." ; 22
	.db 125
	.strz "THIS IS A SMALL CHAMBER HOUSING WHAT APPEARS TO BE A LARGE, ELECTRICALLY POWERED, WATER PUMP.  THE ONLY EXIT IS TO THE SOUTH." ; 23
	.db 43
	.strz "THIS IS A LOW POINT IN THE MAIN E-W TUNNEL." ; 24
	.db 60
	.strz "THIS IS A LARGE CHAMBER.  THE ONLY EXIT IS TO THE NORTHEAST." ; 25
	.db 120
	.strz "THIS IS THE BASE OF A VENTILATION SHAFT. RUNGS ANCHORED INTO THE CONCRETE LEAD UP, WHILE AN EXIT LEADS TO THE SOUTHEAST." ; 26
	.db 52
	.strz "YOU ARE ON A LADDER HALF-WAY UP A VENTILATION SHAFT." ; 27
	.db 104
	.strz "YOU ARE AT THE TOP OF A VENTILATION SHAFT. A METAL CUPOLA, HELD IN PLACE BY LARGE BOLTS, CAPS THE SHAFT." ; 28
	.db 127
	.strz "YOU ARE STANDING ATOP A HIGH ESCARPMENT. IN THE DISTANCE, THE SPIRES ON THE GOTHIC CATHEDRAL OF PRAGUE ARE JUST BARELY VISIBLE." ; 29
	.db 64
	.strz "A PILE OF DAMP LEAVES, BLOWN IN BY THE WIND, LIES ON THE GROUND." ; 30
	.db 49
	.strz "THERE IS A LARGE TABLE IN THE CENTER OF THE ROOM." ; 31
	.db 49
	.strz "THE DATE ON THE STAMP IS SET TO MARCH 10TH, 1945." ; 32
	.db 61
	.strz "A RUBBER STAMP, USED FOR POSTMARKING MAIL, LIES ON THE TABLE." ; 33
	.db 35
	.strz "THE METAL LOCK INSET INTO THE DOOR." ; 34
	.db 48
	.strz "THE FLASHLIGHT IS RUSTED SHUT, BUT OTHERWISE OK." ; 35
	.db 42
	.strz "A DISCARDED FLASHLIGHT LIES ON THE GROUND." ; 36
	.db 85
	.strz "THE CUBE IS ABOUT ONE FOOT ON EACH SIDE.  EMBOSSED IN THE SIDE IS THE WORD 'NATRIUM'." ; 37
	.db 35
	.strz "A LARGE WHITE CUBE SITS ON A SHELF." ; 38
	.db 87
	.strz "THE INSIDE OF THE BOWL IS CHARRED. IT APPEARS IT WAS USED AS A PLACE TO BURN DOCUMENTS." ; 39
	.db 35
	.strz "A FILTHY TOILET SITS IN THE CORNER." ; 40
	.db 94
	.strz "THE CHARRED PAPERS HAVE TURNED INTO A UNPLEASANT GUNK AS A RESULT OF THE CAVE'S HIGH HUMIDITY." ; 41
	.db 66
	.strz "THE METAL LIGHTER IS ADORNED WITH A RAISED EAGLE HOLDING A WREATH." ; 42
	.db 49
	.strz "A FORGOTTEN CIGARETTE LIGHTER LIES ON THE GROUND." ; 43
	.db 50
	.strz "RISING WATER BLOCKS THE WESTERN END OF THE TUNNEL." ; 44
	.db 74
	.strz "THE GERMAN HELMET IS HEAVILY RUSTED.  THE INSIDE WEBBING HAS DETERIORATED." ; 45
	.db 36
	.strz "A RUSTING HELMET LIES ON THE GROUND." ; 46
	.db 81
	.strz "A LARGE MACHINE WITH NUMEROUS PIPES RUNNING THROUGH IT OCCUPIES MOST OF THE ROOM." ; 47
	.db 89
	.strz "THERE IS A SMALL HOLE IN THE TOP.  A WINDOW ON THE SIDE REVEALS IT IS OUT OF ELECTROLYTE." ; 48
	.db 69
	.strz "A LARGE, WET CELL BATTERY, WIRED TO THE MACHINERY, LIES ON THE FLOOR." ; 49
	.db 41
	.strz "THE CUPOLA IS A SMALL, RAISED STEEL DOME." ; 50
	.db 34
	.strz "A RUSTED WRENCH LIES ON THE FLOOR." ; 51
	.db 42
	.strz "YOUR NOSE IS FINE. STOP WORRYING ABOUT IT." ; 52
	.db 43
	.strz "THE SUN IS HIDDEN BEHIND THE GRAY OVERCAST." ; 53
	.db 34
	.strz "THE NEEDLE INDICATES ZERO VOLTAGE." ; 54
	.db 58
	.strz "A VOLTMETER, WIRED TO THE BATTERY, IS AFFIXED TO THE WALL." ; 55
	.db 32
	.strz "THE WOODEN CRATE IS NAILED SHUT." ; 56
	.db 64
	.strz "A LARGE WOODEN CRATE OCCUPIES SITS IN THE CENTER OF THE CHAMBER." ; 57
	.db 39
	.strz "THE FORMER WOODEN CRATE IS NOW SMASHED." ; 58
	.db 50
	.strz "A PILE OF BROKEN WOOD (FORMERLY A CRATE), IS HERE." ; 59
	.db 13
	.strz "OOOOH! SHINY!" ; 60
	.db 48
	.strz "SHINY GOLD BARS LIE ON TOP OF THE SMASHED CRATE." ; 61
	.db 46
	.strz "THE LARGE BLOCK OF SALT DISOLVES IN THE WATER." ; 62
	.db 33
	.strz "HIGH ABOVE, YOU CAN HEAR BUZZING." ; 63
	.db 107
	.strz "AS YOU SQUIRM THROUGH THE NARROW GAP, THE ROCKS GIVE WAY CAUSING YOU TO FALL MANY FEET TO THE TUNNEL FLOOR." ; 64
	.db 59
	.strz "YOU CAN'T FIT THROUGH THE OPENING WHILE CARRYING THE CRATE." ; 65
	.db 63
	.strz "AFTER SEVERAL ATTEMPTS, YOU MANAGE TO UNLOCK AND OPEN THE DOOR." ; 66
	.db 33
	.strz "YOU HAVE NOTHING TO DO THAT WITH." ; 67
	.db 110
	.strz "FUELED BY THE DRAFT FROM ABOVE, THE LEAVES EVAPORATE IN CLOUD OF ACRID SMOKE WHICH RISES QUICKLY UP THE SHAFT." ; 68
	.db 35
	.strz "YOU CAN'T DO THAT WHILE ON A LADDER" ; 69
	.db 63
	.strz "THE LEAVES SMOLDER A BIT, THEN GO OUT DUE TO THE HIGH HUMIDITY." ; 70
	.db 91
	.strz "THE LEAVES (WHICH YOU ARE CARRYING) IGNTIE. UNFORTUNATELY, THE FIRE RAPIDLY SPREADS TO YOU." ; 71
	.db 34
	.strz "NEXT TIME TRY DROPPING THE LEAVES." ; 72
	.db 28
	.strz "YOU HAVE NO IGNITION SOURCE." ; 73
	.db 108
	.strz "AS YOU RELUCTANTLY PICK UP THE PAPPERS, THEY DISINTEGRATE INTO GUNK, LEAVING YOU WITH A BLACKENED PAPERCLIP." ; 74
	.db 16
	.strz "IT'S ALREADY ON." ; 75
	.db 6
	.strz "CLICK." ; 76
	.db 17
	.strz "IT'S ALREADY OFF." ; 77
	.db 39
	.strz "THE SALTY CAVE WATER TASTES UNPLEASANT." ; 78
	.db 64
	.strz "AS THE BATTERY BEGINS CHARGES, THE PUMPS GRADUALY BEING WORKING." ; 79
	.db 35
	.strz "THE BATTERY IS FULL OF ELECTROLYTE." ; 80
	.db 40
	.strz "THE NEEDLE INDICATES CURRENT IS FLOWING." ; 81
	.db 123
	.strz "THIS IS A LOW POINT AT THE END OF AN E-W TUNNEL. THE MAIN TUNNEL LEADS EAST. SMALLER PASSAGES LEAD NORTHWEST AND SOUTHWEST." ; 82
	.db 20
	.strz "THE HELMET IS EMPTY." ; 83
	.db 26
	.strz "YOU DON'T HAVE THE HELMET." ; 84
	.db 100
	.strz "THE REMAINING WATER IN THE TANK WASHES AWAY THE PAPER LEAVING A PAPERCLIP AT THE BOTTOM OF THE BOWL." ; 85
	.db 16
	.strz "NOTHING HAPPENS." ; 86
	.db 13
	.strz "AAAAARRRRRRR." ; 87
	.db 105
	.strz "WITH SOME DIFFICULTY, YOU MANAGE TO REMOVE THE BOLTS. AS YOU PUSH THE CUPOLA UP, IT FALLS OUT OF THE WAY." ; 88
	.db 45
	.strz "THERE IS A HEAVY, METAL CUPOLA ON THE GROUND." ; 89
	.db 49
	.strz "THE HEAVY METAL LID HAS STARTED RUSTING WITH AGE." ; 90
	.db 77
	.strz "YOU ARE AT THE TOP OF A VENTILATION SHAFT. ABOVE, AN OPEN HOLE LEADS OUTSIDE." ; 91
	.db 25
	.strz "YOU'VE ALREADY DONE THAT." ; 92
	.db 23
	.strz "YOU CAN'T DO THAT HERE." ; 93
	.db 40
	.strz "YOU DON'T HAVE ANYTHING TO DO THAT WITH." ; 94
	.db 41
	.strz "THE HELMET IS NOW FILLED WITH SALT WATER." ; 95
	.db 27
	.strz "THE HELMET IS ALREADY FULL." ; 96
	.db 23
	.strz "THERE IS NO WATER HERE." ; 97
	.db 22
	.strz "YOU CAN'T UNBOLT THAT." ; 98
	.db 63
	.strz "FOR SOME INEXPLICABLE REASON YOU DECIDE TO JUMP OFF THE LADDER." ; 99
	.db 105
	.strz "UNFORTUNATELY, THE ROCK FLOOR AT THE BOTTOM OF THE SHAFT ISN'T QUITE AS FORGIVING AS YOU HAD ANTICIPATED." ; 100
	.db 48
	.strz "YOU LAND WITH A THUD AT THE BOTTOM OF THE SHAFT." ; 101
	.db 7
	.strz "WHEEEE!" ; 102
	.db 23
	.strz "YOU CAN'T TURN THAT ON." ; 103
	.db 19
	.strz "***YOU HAVE DIED***" ; 104
	.db 14
	.strz "TIME PASSES..." ; 105
	.db 57
	.strz "THE CRATE FALLS DOWN THE SHAFT AND SMASHES AT THE BOTTOM." ; 106
	.db 34
	.strz "YOU HAVE A STRANGE SENSE OF HUMOR." ; 107
	.db 52
	.strz "YOU HAVE A STRANGE FASCINATION WITH FLUSHING THINGS." ; 108
	.db 36
	.strz "THERE ARE BETTER WAYS TO WASTE TIME." ; 109
	.db 30
	.strz "ARE YOU SOME SORT OF ARSONIST?" ; 110
	.db 20
	.strz "YOU CAN'T PICK THAT." ; 111
	.db 93
	.strz "THERE ARE SEVERAL ENTERTAINING WAYS TO DIE IN THIS ADVENTURE...NO NEED TO SPEED THINGS ALONG." ; 112
	.db 33
	.strz "THE KEY HAS LONG SINCE BEEN LOST." ; 113
	.db 0
