;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; DescriptionTable6809.asm
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

description_table
	.db 30
	.strz "YOU NOTICE NOTHING UNEXPECTED." ; 0
	.db 9
	.strz "OFFSCREEN" ; 1
	.db 22
	.strz "YOU SHOULDN'T BE HERE." ; 2
	.db 65
	.strz "YOU'RE A WONDERFUL PERSON. YOU SHOULDN'T CARE WHAT YOU LOOK LIKE." ; 3
	.db 61
	.strz "THIS IS THE START OF A PATH THAT WINDS NORTH INTO THE FOREST." ; 4
	.db 80
	.strz "THE HUT IS BARELY LARGE ENOUGH TO PROTECT ONE OR TWO SENTRIES FROM THE ELEMENTS." ; 5
	.db 38
	.strz "A DILAPIDATED GUARD HUT STANDS NEARBY." ; 6
	.db 79
	.strz "YOU ARE INSIDE THE SMALL GUARD HUT. THE OPEN DOORWAY LEADS OUTSIDE TO THE WEST." ; 7
	.db 181
	.strz "YOU ARE AT THE MOUTH OF A LARGE, COLLAPSED TUNNEL CUT INTO A STEEP HILLSIDE TO THE NORTH. A DIRT PATH RUNS EAST AND WEST AROUND THE ESCARPMENT AND WINDS SOUTH INTO THE THICK FOREST." ; 8
	.db 104
	.strz "YOU ARE ON A DIRT PATH CURVING AROUND THE BASE OF A ROCKY HILLSIDE. THE PATH EXTENDS WEST AND NORTHEAST." ; 9
	.db 102
	.strz "YOU ARE ON A DIRT PATH CURVING AROUND THE BASE OF A ROCKY HILLSIDE. THE PATH EXTENDS BACK TO THE EAST." ; 10
	.db 237
	.strz "YOU ARE ON THE EASTERN EDGE OF A ROCKY HILLSIDE.  A LARGE,DARK TUNNEL EXTENDS WESTWARD INTO THE HILLSIDE.  ALTHOUGH IT APPEARS ATTEMPTS WERE MADE TO DEMOLISH IT, IT MAY BE POSSIBLE TO CLIMB OVER THE DEBRIS. A DIRT PATH EXTENDS SOUTHWEST." ; 11
	.db 135
	.strz "YOU ARE ONTOP OF A LARGE ROCK PILE JUST INSIDE THE MOUTH OF A LARGE TUNNEL. TO THE WEST, THE PILE DROPS PRECIPITOUSLY INTO THE DARKESS." ; 12
	.db 149
	.strz "YOU ARE AT THE EASTERN END OF AN EAST-WEST TUNNEL. TO THE EAST, A HUGE DEBRIS PILE, THE RESULT OF INTENTIONAL DEMOLITION, COMPLETELY BLOCKS THE EXIT." ; 13
	.db 67
	.strz "YOU ARE AT A TUNNEL JUNCTION. TUNNELS EXTEND EAST, WEST, AND SOUTH." ; 14
	.db 95
	.strz "THIS IS A SMALL OFFICE AREA. DOORWAYS LEADS NORTH AND SOUTH.  A STORAGE CLOSEST IS TO THE EAST." ; 15
	.db 47
	.strz "THIS IS A DANK LAVATORY. A DOORWAY LEADS NORTH." ; 16
	.db 29
	.strz "THE DOOR SPORTS A LARGE LOCK." ; 17
	.db 52
	.strz "THIS IS A CRAMPED STORAGE CLOSET. A DOOR LEADS WEST." ; 18
	.db 111
	.strz "THIS IS A LONG EAST-WEST TUNNEL THAT SLOPES DOWNWARD AT TOWARD THE WEST. A SMALLER TUNNEL EXTENDS TO THE NORTH." ; 19
	.db 72
	.strz "THIS IS A FOUR WAY JUNCTION.  PASSAGES LEAD NORTH, SOUTH, EAST AND WEST." ; 20
	.db 185
	.strz "THIS IS A LARGE, NORTH-SOUTH TUNNEL THAT ENDS ABRUPTLY WHERE IT HAS COLLAPSED.  SCORCH MARKS WOULD SUGGEST THE TUNNEL ENTRANCE WAS DESTROYED DELIBERATELY. THE ONLY EXIT IS TO THE NORTH." ; 21
	.db 174
	.strz "YOU HAVE ENTERED A VAST SUBTERANEAN WORKHALL CARVED OUT OF THE NATIVE LIMESTONE. IT WAS APPARENTLY GUTTED OF EQUIPMENT BEFORE IT WAS ABANDONED. THERE IS AN EXIT TO THE SOUTH." ; 22
	.db 125
	.strz "THIS IS A SMALL CHAMBER HOUSING WHAT APPEARS TO BE A LARGE, ELECTRICALLY POWERED, WATER PUMP.  THE ONLY EXIT IS TO THE SOUTH." ; 23
	.db 43
	.strz "THIS IS A LOW POINT IN THE MAIN E-W TUNNEL." ; 24
	.db 60
	.strz "THIS IS A SMALL CHAMBER.  THE ONLY EXIT IS TO THE NORTHEAST." ; 25
	.db 120
	.strz "THIS IS THE BASE OF A VENTILATION SHAFT. RUNGS ANCHORED INTO THE CONCRETE LEAD UP, WHILE AN EXIT LEADS TO THE SOUTHEAST." ; 26
	.db 52
	.strz "YOU ARE ON A LADDER HALF-WAY UP A VENTILATION SHAFT." ; 27
	.db 105
	.strz "YOU ARE AT THE TOP OF A VENTILATION SHAFT. A METAL CUPOLA, HELD IN PLACE BY LARGE SCREWS, CAPS THE SHAFT." ; 28
	.db 127
	.strz "YOU ARE STANDING ATOP A HIGH ESCARPMENT. IN THE DISTANCE, THE SPIRES ON THE GOTHIC CATHEDRAL OF PRAGUE ARE JUST BARELY VISIBLE." ; 29
	.db 64
	.strz "A PILE OF DAMP LEAVES, BLOWN IN BY THE WIND, LIES ON THE GROUND." ; 30
	.db 49
	.strz "THERE IS A LARGE TABLE IN THE CENTER OF THE ROOM." ; 31
	.db 144
	.strz "THE DOCUMENTS APPEAR TO BE IN GERMAN. A STAMP MARK SHOWS THE DATE OF MARCH,1945. DETERIORATION HAS RENDERED THE REST OF THE DOCUMENTS ILLEGIBLE." ; 32
	.db 38
	.strz "SOME MOLDY DOCUMENTS LIE ON THE TABLE." ; 33
	.db 35
	.strz "THE METAL LOCK INSET INTO THE DOOR." ; 34
	.db 48
	.strz "THE FLASHLIGHT IS RUSTED SHUT, BUT OTHERWISE OK." ; 35
	.db 42
	.strz "A DISCARDED FLASHLIGHT LIES ON THE GROUND." ; 36
	.db 85
	.strz "THE CUBE IS ABOUT ONE FOOT ON EACH SIDE.  EMBOSSED IN THE SIDE IS THE WORD 'NATRIUM'." ; 37
	.db 35
	.strz "A LARGE WHITE CUBE SITS ON A SHELF." ; 38
	.db 35
	.strz "A FILTHY TOILET SITS IN THE CORNER." ; 39
	.db 87
	.strz "THE INSIDE OF THE BOWL IS CHARRED. IT APPEARS IT WAS USED AS A PLACE TO BURN DOCUMENTS." ; 40
	.db 94
	.strz "THE CHARRED PAPERS HAVE TURNED INTO A UNPLEASANT GUNK AS A RESULT OF THE CAVE'S HIGH HUMIDITY." ; 41
	.db 66
	.strz "THE METAL LIGHTER IS ADORNED WITH A RAISED EAGLE HOLDING A WREATH." ; 42
	.db 49
	.strz "A FORGOTTEN CIGARETTE LIGHTER LIES ON THE GROUND." ; 43
	.db 50
	.strz "RISING WATER BLOCKS THE WESTERN END OF THE TUNNEL." ; 44
	.db 74
	.strz "THE GERMAN HELMET IS HEAVILY RUSTED.  THE INSIDE WEBBING HAS DETERIORATED." ; 45
	.db 36
	.strz "A RUSTING HELMET LIES ON THE GROUND." ; 46
	.db 81
	.strz "A LARGE MACHINE WITH NUMEROUS PIPES RUNNING THROUGH IT OCCUPIES MOST OF THE ROOM." ; 47
	.db 89
	.strz "THERE IS A SMALL HOLE IN THE TOP.  A WINDOW ON THE SIDE REVEALS IT IS OUT OF ELECTROLYTE." ; 48
	.db 69
	.strz "A LARGE, WET CELL BATTERY, WIRED TO THE MACHINERY, LIES ON THE FLOOR." ; 49
	.db 46
	.strz "THE LARGE BLOCK OF SALT DISOLVES IN THE WATER." ; 50
	.db 37
	.strz "HIGH ABOVE, YOU CAN HEAR THE BUZZING." ; 51
	.db 107
	.strz "AS YOU SQUIRM THROUGH THE NARROW GAP, THE ROCKS GIVE WAY CAUSING YOU TO FALL MANY FEET TO THE TUNNEL FLOOR." ; 52
	.db 63
	.strz "AFTER SEVERAL ATTEMPTS, YOU MANAGE TO UNLOCK AND OPEN THE DOOR." ; 53
	.db 33
	.strz "YOU HAVE NOTHING TO DO THAT WITH." ; 54
	.db 110
	.strz "FUELED BY THE DRAFT FROM ABOVE, THE LEAVES EVAPORATE IN CLOUD OF ACRID SMOKE WHICH RISES QUICKLY UP THE SHAFT." ; 55
	.db 35
	.strz "YOU CAN'T DO THAT WHILE ON A LADDER" ; 56
	.db 63
	.strz "THE LEAVES SMOLDER A BIT, THEN GO OUT DUE TO THE HIGH HUMIDITY." ; 57
	.db 65
	.strz "LIGHTING A PILE OF LEAVES WHICH YOU ARE CARRYING WOULD BE UNWISE." ; 58
	.db 28
	.strz "YOU HAVE NO IGNITION SOURCE." ; 59
	.db 108
	.strz "AS YOU RELUCTANTLY PICK UP THE PAPPERS, THEY DISINTEGRATE INTO GUNK, LEAVING YOU WITH A BLACKENED PAPERCLIP." ; 60
	.db 16
	.strz "IT'S ALREADY ON." ; 61
	.db 6
	.strz "CLICK." ; 62
	.db 17
	.strz "IT'S ALREADY OFF." ; 63
	.db 0
